FROM node:21-bookworm-slim@sha256:c88704924204ee6d4e9da02275a8fd27355502f7177e4175cd0d3a4375a9c9c8

RUN apt update && apt upgrade && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y git && \
    rm -rf /var/lib/apt/lists/*